services:
  paddleocr-server:
    build: .
    image: jarvis1tube/paddleocr-server:gpu
    container_name: paddleocr-server
    ports:
      - "8080:8080"
    volumes:
      - ${USERPROFILE:-.}/.paddlex:/root/.paddlex
    environment:
      - OCR_HOST=0.0.0.0
      - OCR_PORT=8080
      - OCR_LOG_LEVEL=info
      - OCR_LANG=en
      - OCR_ENABLE_HIGH_INFERENCE=true
      - OCR_USE_TENSORRT=true
      - OCR_PRECISION=fp32
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
